apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: petclinic
  labels:
    app.kubernetes.io/name: admin-server
    app.kubernetes.io/part-of: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin-server
        app.kubernetes.io/part-of: petclinic
    spec:
      containers:
        - name: admin-server
          image: tejupagudala/admin-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: SPRING_CONFIG_IMPORT
              value: ""
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SPRING_APPLICATION_NAME
              value: admin-server
            - name: SERVER_PORT
              value: "9090"
            - name: EUREKA_CLIENT_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
              value: http://discovery-server:8761/eureka/
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
