apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: petclinic
  labels:
    app.kubernetes.io/name: admin-server
    app.kubernetes.io/part-of: spring-petclinic
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: admin-server
  ports:
    - name: http
      port: 9090
      targetPort: 9090
